version: "3"

services:
  vue-storefront:
    build:
      context: ./VueStoreFront
    ports:
      - "3000:3000"

  metabase:
    build:
      context: ./metabase
    ports:
      - "3001:3001"

  magento:
    build:
      context: ./magento
    ports:
      - "8080:80"
